In [1]:
import torch
# !pip install pytorch torchvision cudatoolkit=10.1 -c pytorch


In [2]:
a=torch.ones(3)
print(a)
print(a[1])
print(float(a[1]))

tensor([1., 1., 1.])
tensor(1.)
1.0


In [3]:
points = torch.zeros(6) # <1>
points[0] = 4.0 # <2>
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
print(points)

tensor([4., 1., 5., 3., 2., 1.])


In [4]:
c = torch.tensor([1,2,3,4,5])
print(c)
print(c[1])
print(int(c[1]))

tensor([1, 2, 3, 4, 5])
tensor(2)
2


In [5]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.2], [2.0, 1.0]])
print(points)
print(points.shape)

tensor([[4.0000, 1.0000],
        [5.0000, 3.2000],
        [2.0000, 1.0000]])
torch.Size([3, 2])


In [6]:
pointsZero = torch.zeros(3, 2)
print(pointsZero)
print(pointsZero[1])
print(pointsZero[1][1])

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([0., 0.])
tensor(0.)


In [7]:
qq = points[1]
print(qq)
qq.storage()

tensor([5.0000, 3.2000])


 4.0
 1.0
 5.0
 3.200000047683716
 2.0
 1.0
[torch.FloatStorage of size 6]

In [8]:
pointsZero.storage()[2]

0.0

In [9]:
second_point = points[1]
second_point.size()

torch.Size([2])

In [10]:
print(second_point.storage_offset())
print(second_point.stride())

2
(1,)


In [11]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [12]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [13]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [14]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [15]:
id(points.storage()) == id(points_t.storage())


True

In [16]:
points.stride()

(2, 1)

In [17]:
points_t.stride()

(1, 2)

In [18]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape

torch.Size([3, 4, 5])

In [19]:
transpose_t

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [20]:
transpose_t.shape

torch.Size([5, 4, 3])

In [21]:
some_t.stride()


(20, 5, 1)

In [22]:
transpose_t.stride()

(1, 5, 20)

In [23]:
points.is_contiguous()

True

In [24]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [25]:
points_t.storage()


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [26]:
points_t.stride()


(1, 2)

In [27]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [28]:
points_t_cont.stride()


(3, 1)

In [29]:
points_t_cont.storage()


 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.FloatStorage of size 6]

In [30]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [31]:
short_points.dtype


torch.int16

In [32]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [33]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [34]:
points_64 = torch.rand(5, dtype=torch.double)  # <1>
points_short = points_64.to(torch.short)
points_64 * points_short  # works from PyTorch 1.3 onwards

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [35]:
# reset points back to original value
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [36]:
some_list = list(range(6))
some_list[:]     # <1>
some_list[1:4]   # <2>
some_list[1:]    # <3>
some_list[:4]    # <4>
some_list[:-1]   # <5>
some_list[1:4:2] # <6>

[1, 3]

In [37]:
points[1:]       # <1>
points[1:, :]    # <2>
points[1:, 0]    # <3>
points[None]     # <4>

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [38]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [39]:
points = torch.from_numpy(points_np)

In [40]:
torch.save(points, 'ourpoints.t')

In [41]:
with open('ourpoints.t','wb') as f:
   torch.save(points, f)

In [42]:
points = torch.load('ourpoints.t')


In [43]:
with open('ourpoints.t','rb') as f:
   points = torch.load(f)

In [44]:
import h5py

f = h5py.File('ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

In [45]:
f = h5py.File('ourpoints.hdf5', 'r')
dset = f['coords']
last_points = dset[-2:]

In [46]:
last_points = torch.from_numpy(dset[-2:])
f.close()

In [47]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

In [48]:
points_gpu = points.to(device='cuda')

In [49]:
points_gpu = points.to(device='cuda:0')


In [50]:
points = 2 * points  # <1>
points_gpu = 2 * points.to(device='cuda')  # <2>

In [51]:
points_gpu = points_gpu + 4

In [52]:
points_cpu = points_gpu.to(device='cpu')

In [53]:
points_gpu = points.cuda()  # <1>
points_gpu = points.cuda(0)
points_cpu = points_gpu.cpu()

In [54]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [55]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)

a.shape, a_t.shape


(torch.Size([3, 2]), torch.Size([2, 3]))

In [56]:
a = torch.ones(3, 2)

In [57]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])